name: phenoplier-cli
channels:
  - conda-forge
dependencies:
  - python=^3.10
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.8.*
  - r-base=4.1.*
  - rpy2=3.5.*
