[tool.poetry]
name = "phenoplier"
version = "0.1.0"
description = ""
authors = ["Haoyu Zhang"]
license = "BSD-2-Clause Plus Patent License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
typer = "0.12.*"
rich = "13.7.*"
pytest = "8.1.*"
pandas = "2.2.*"
scipy = "1.13.*"
statsmodels = "0.14.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
