# Core Settings
# Base working directory for the project, where data, results, and software are stored
ROOT_DIR = "/tmp/phenoplier"
# Directory stores input data
DATA_DIR = "@format {this.ROOT_DIR}/data"
# Directory stores output data
RESULT_DIR = "@format {this.ROOT_DIR}/results"
# Directory stores third-party applications
SOFTWARE_DIR = "@format {this.ROOT_DIR}/software"
CONDA_ENVS_DIR = "@format {this.SOFTWARE_DIR}/conda_envs"

# General Settings
[GENERAL]
BIOMART_GENES_INFO_FILE = "@format {this.DATA_DIR}/biomart_genes_hg38.csv.gz"
TERM_ID_LABEL_FILE = "@format {this.DATA_DIR}/term_id_labels.tsv.gz"
TERM_ID_XREFS_FILE = "@format {this.DATA_DIR}/term_id_xrefs.tsv.gz"
EUR_LD_REGIONS_FILE = "@format {this.DATA_DIR}/eur_ld.bed.gz"
[GENERAL.LIFTOVER]
BASE_DIR = "@format {this.DATA_DIR}/liftover"
CHAINS_DIR = "@format {this.GENERAL.LIFTOVER.BASE_DIR}/chains"
HG19_TO_HG38 = "@format {this.GENERAL.LIFTOVER.CHAINS_DIR}/hg19ToHg38.over.chain.gz"

# Gene Module Model settings
[GENE_MODULE_MODEL]
# Root directory for MultiPLIER
BASE_DIR = "@format {this.DATA_DIR}/multiplier"
# MultiPLIER model files
MODEL_SUMMARY_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_summary.pkl"
MODEL_Z_MATRIX_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_z.pkl"
#MODEL_Z_MATRIX_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/htp_plier_model_k0.75_frac1_Zmatrix.pkl"
# not used below
#MODEL_B_MATRIX_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_b.pkl"
#MODEL_U_MATRIX_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_u.pkl"
#MODEL_U_AUC_MATRIX_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_u_auc.pkl"
# not used above
MODEL_METADATA_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/multiplier_model_metadata.pkl"
# RECOUNT2_MODEL_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/recount_PLIER_model.RDS"
BANCHEREAU_MCPCOUNTER_NEUTROPHIL_FILE = "@format {this.GENE_MODULE_MODEL.BASE_DIR}/Banchereau_MCPcounter_neutrophil_LV.tsv"

# TWAS Settings
[TWAS]
# Root directory for PhenomeXcan
BASE_DIR = "@format {this.DATA_DIR}/phenomexcan"
# Genes metadata and mappings
GENES_METADATA_DIR = "@format {this.TWAS.BASE_DIR}/genes_metadata"
GENE_MAP_ID_TO_NAME = "@format {this.TWAS.GENES_METADATA_DIR}/genes_mapping_id_to_name.pkl"
GENE_MAP_NAME_TO_ID = "@format {this.TWAS.GENES_METADATA_DIR}/genes_mapping_name_to_id.pkl"
TRAITS_FULLCODE_TO_EFO_MAP_FILE = "@format {this.TWAS.BASE_DIR}/phenomexcan_traits_fullcode_to_efo.tsv"
# Gene association results
GENE_ASSOC_DIR = "@format {this.TWAS.BASE_DIR}/gene_assoc"
#SPREDIXCAN_MASHR_ZSCORES_FOLDER = "@format {this.TWAS.GENE_ASSOC_DIR}/spredixcan"
# S-MultiXcan
SMULTIXCAN_DATA_BASE_DIR = "@format {this.DATA_DIR}/smultixcan"
SMULTIXCAN_DATA_RAPID_GWAS = "@format {this.TWAS.SMULTIXCAN_DATA_BASE_DIR}/rapid_gwas"
SMULTIXCAN_DATA_RAPID_GWAS_ZIP = "@format {this.TWAS.SMULTIXCAN_DATA_BASE_DIR}/rapid_gwas.zip"
SMULTIXCAN_DATA_GTEX_GWAS = "@format {this.TWAS.SMULTIXCAN_DATA_BASE_DIR}/gtex_gwas"
SMULTIXCAN_MASHR_ZSCORES_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/smultixcan-mashr-zscores.pkl"
SMULTIXCAN_EFO_PARTIAL_MASHR_ZSCORES_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/smultixcan-efo_partial-mashr-zscores.pkl"
SMULTIXCAN_EFO_PARTIAL_MASHR_PVALUES_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/smultixcan-efo_partial-mashr-pvalues.pkl"
SMULTIXCAN_MASHR_PVALUES_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/smultixcan-mashr-pvalues.pkl"
FASTENLOC_TORUS_RCP_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/fastenloc-torus-rcp.pkl"
FASTENLOC_EFO_PARTIAL_TORUS_RCP_FILE = "@format {this.TWAS.GENE_ASSOC_DIR}/fasten loc-efo_partial-torus-rcp.pkl"
# GWAS info
RAPID_GWAS_PHENO_INFO_FILE = "@format {this.TWAS.BASE_DIR}/phenotypes.both_sexes.tsv.gz"
RAPID_GWAS_DATA_DICT_FILE = "@format {this.TWAS.BASE_DIR}/UKB_Data_Dictionary_Showcase.tsv"
GTEX_GWAS_PHENO_INFO_FILE = "@format {this.TWAS.BASE_DIR}/gtex_gwas_phenotypes_metadata.tsv"
# LD blocks
[TWAS.LD_BLOCKS]
BASE_DIR = "@format {this.TWAS.BASE_DIR}/ld_blocks"
1000G_GENOTYPE_DIR = "@format {this.TWAS.LD_BLOCKS.BASE_DIR}/reference_panel_1000G"
GTEX_V8_GENOTYPE_DIR = "@format {this.TWAS.LD_BLOCKS.BASE_DIR}/reference_panel_gtex_v8"
OUTPUT_FILE_NAME = "snps_chr_blocks_cov.h5"
# Predictions models
[TWAS.PREDICTION_MODELS]
BASE_DIR = "@format {this.TWAS.BASE_DIR}/prediction_models"
## Mashr models
MASHR = "@format {this.TWAS.PREDICTION_MODELS.BASE_DIR}/mashr"
MASHR_PREFIX = "mashr_"

# UK Biobank Settings
[UK_BIOBANK]
BASE_DIR = "@format {this.DATA_DIR}/uk_biobank"
CODINGS_DIR = "@format {this.UK_BIOBANK.BASE_DIR}/codings"
CODING_3_FILE = "@format {this.UK_BIOBANK.CODINGS_DIR}/config3.tsv"
CODING_6_FILE = "@format {this.UK_BIOBANK.CODINGS_DIR}/config6.tsv"
UKBCODE_TO_EFO_MAP_FILE = "@format {this.UK_BIOBANK.BASE_DIR}/UK_Biobank_master_file.tsv"

# External Dependency Settings
[DEPENDENCIES]
[DEPENDENCIES.GWAS_IMPUTATION]
BASE_DIR = "@format {this.SOFTWARE_DIR}/summary_gwas_imputation"
CONDA_ENV = "@format {this.CONDA_ENVS_DIR}/summary_gwas_imputation"

# Result Settings
[RESULTS]
BASE_DIR = "@format {this.RESULT_DIR}"
GLS = "@format {this.RESULTS.BASE_DIR}/gls"
