name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      #----------------------------------------------
      #       install Conda
      #----------------------------------------------
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - name: Install dependencies
        run: |
          chmod +x scripts/setup_env.sh
          ./scripts/setup_env.sh
          conda init bash
          source ~/.bashrc
          conda activate phenoplier-cli-dev
          echo "Using conda environment: ${CONDA_DEFAULT_ENV}"
          poetry -V
          phenoplier -v
      #----------------------------------------------
      #  -----  setup data  -----
      #----------------------------------------------
      - name: Setup data
        run: |
          conda init bash
          source ~/.bashrc
          conda activate phenoplier-cli-dev
          export ENV_FOR_DYNACONF=test
          phenoplier get test
      #----------------------------------------------
      #  -----  run tests  -----
      #----------------------------------------------
      - name: Run tests
        run: |
          conda init bash
          source ~/.bashrc
          conda activate phenoplier-cli-dev
          export ENV_FOR_DYNACONF=test
          PYTHONPATH=. pytest -rs --color=yes test/
          # coverage report
